#ifndef __GUIMainFrame__
#define __GUIMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "GUI.h"
#include "frame.h"
#include <wx/artprov.h>
#include <wx/xrc/xmlres.h>
#include <wx/panel.h>
#include <wx/gdicmn.h>
#include <wx/font.h>
#include <wx/colour.h>
#include <wx/settings.h>
#include <wx/string.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/slider.h>
#include <wx/frame.h>
#include <memory>
#include <wx/wxprec.h>
#include <wx/button.h>
#include <wx/bitmap.h>
#include <wx/image.h>
#include <wx/icon.h>
#include <wx/checkbox.h>
#include <wx/gauge.h>
#include <wx/textctrl.h>
#include <wx/choice.h>
#include <wx/frame.h>
#include <wx/colordlg.h>
#include <wx/dcbuffer.h>
#include <wx/filefn.h> 
#include <wx/wxprec.h>
#include <wx/artprov.h>
#include <wx/xrc/xmlres.h>
#include <wx/panel.h>
#include <wx/gdicmn.h>
#include <wx/font.h>
#include <wx/colour.h>
#include <wx/settings.h>
#include <wx/string.h>
#include <wx/sizer.h>
#include <wx/button.h>
#include <wx/bitmap.h>
#include <wx/image.h>
#include <wx/icon.h>
#include <wx/checkbox.h>
#include <wx/slider.h>
#include <wx/gauge.h>
#include <wx/textctrl.h>
#include <wx/choice.h>
#include <wx/frame.h>
#include <wx/wxprec.h>
#include <wx/colordlg.h>
#include <wx/dcbuffer.h>
#include <wx/filefn.h> s

//// end generated include

/** Implementing MainFrame */
class GUIMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void m_panel2OnSize(wxSizeEvent& event);
		void m_slider_leftShoulderOnScroll( wxScrollEvent& event );
		void m_slider_leftElbowOnScroll( wxScrollEvent& event );
		void m_slider_leftHipOnScroll( wxScrollEvent& event );
		void m_slider_leftLegOnScroll(wxScrollEvent& event);
		void m_slider_leftKneeOnScroll( wxScrollEvent& event );
		void m_slider_neckOnScroll( wxScrollEvent& event );
		void m_slider_rightShoulderOnScroll( wxScrollEvent& event );
		void m_slider_rightElbowOnScroll( wxScrollEvent& event );
		void m_slider_rightHipOnScroll( wxScrollEvent& event );
		void m_slider_rightLegOnScroll(wxScrollEvent& event);
		void m_slider_rightKneeOnScroll( wxScrollEvent& event );
		void m_slider_spineOnScroll( wxScrollEvent& event );
		void m_slider_endOfSpineOnScroll( wxScrollEvent& event );
		wxBitmap bitmapBuffer;

	public:
		/** Constructor */
		GUIMainFrame( wxWindow* parent );
		//
	//// end generated class members'
		void Draw();
	private:
	Frame szkieletor = { Point(-30.0,100.0),Point(30.0,100.0),Point(-20.0,60.0),Point(20.0,60.0),Point(0.0,60.0),Point(0.0,30.0),Point(0.0,0.0),Point(-20.0,0.0),Point(20.0,0.0),Point(-50.0,0.0),Point(50.0,0.0),Point(-80.0,0.0),Point(80.0,0.0),Point(-40.0,140.0),Point(40.0,140.0),Point(0.0,-20.0)};



};

#endif // __GUIMainFrame__
